version: '3.9'
services:
  message-processor:
    image: messaging-client-processor:latest
    env_file: "settings.env"
    build:
      context: messaging-client-scenarios
    command: ["java", "-Dreactor.schedulers.defaultBoundedElasticSize=250", "org.springframework.boot.loader.launch.JarLauncher", "--scenario=ServiceBusProcessorScenario"]
    environment:
      - MAX_CONCURRENT_SESSIONS=6 # Process up to 'MAX_CONCURRENT_SESSIONS' sessions.
      - MAX_CONCURRENT_CALLS=3    # Process each session with up to 'MAX_CONCURRENT_CALLS' concurrent calls.
      - SESSION_IDLE_TIMEOUT_IN_SECONDS=30 # 30 seconds
      - SESSION_MAX_LOCK_RENEWAL_DURATION_IN_SECONDS=300 # 5 minutes.
    container_name: message-processor
    deploy:
      resources:
        limits:
          cpus: '2'
  message-sender:
    image: messaging-client-sender:latest
    env_file: "settings.env"
    build:
      context: messaging-client-scenarios
    command: ["java", "org.springframework.boot.loader.launch.JarLauncher", "--scenario=ServiceBusSenderScenario"]
    environment:
      - SEND_SESSIONS=12            # Send messages to 'SEND_SESSIONS' sessions.
      - SESSION_ID_MODE=SEQUENTIAL  # How to pick session to send message to: SEQUENTIAL = (0..SEND_SESSIONS..0..SEND_SESSIONS...) or RANDOM = rand(0..SEND_SESSIONS)
      - SECONDS_IN_PERIOD=6
      - SEND_MESSAGES_PER_PERIOD=5 # Send at a rate of 'SEND_MESSAGES_PER_PERIOD' messages per 'SECONDS_IN_PERIOD' (e.g., 5 messages in every 6 seconds).
      - SEND_CONCURRENCY=1          # Send messages 'SEND_CONCURRENCY' concurrent calls.
    container_name: message-sender
    deploy:
      resources:
        limits:
          cpus: '2'
